#=========================================================#
#                      MineM Invoices                     #
#=========================================================#

COMMAND_NAME: "invoice" # The name of the command

INVOICE_SETTINGS:
  STANDARD_DAYS_TO_PAY: 7 # The amount of days that the player has to pay the invoice.

RANK_PERMISSIONS:
  # These are the ranks in-game that have access to sending invoices to players.
  # Without these ranks, players cannot send invoices.
  POLICE:
    PERMISSION: "mineminvoices.police" # This is the permission that the player needs to have to send invoices.
    LIMIT_AMOUNT: 1000.00 # This is the maximum amount that the player can send in an invoice.
    CAN_CREATE_INVOICE: true # This is whether or not the player can create invoices.
    CAN_CANCEL_INVOICE: true # This is whether or not the player can cancel invoices.
    CAN_CHECK_INVOICE: true # This is whether or not the player can check invoices.