name: MineM-Invoices
version: '1.0.0'
main: nl.rubixstudios.minem.invoices.MineMInvoices
author: Djorr
website: https://discord.rubixdevelopment.nl
api-version: 1.13
depend:
  - Vault
  - NBTAPI
commands:
  invoice:
    description: Open invoice menu
    aliases: [factuur]
